import useAuth from "@/hooks/useAuth";
import useFarm from "@/hooks/useFarm";
import { Separator } from "@radix-ui/react-separator";

export default function Signature() {
    const { user } = useAuth();
    const { selectedFarm } = useFarm();
    return <>
        <div className="flex flex-row w-full justify-end mt-auto pr-[100px]">
            <div className="flex flex-col max-w-[400px]">
                <span className="text-start mb-4 text-[12px]">Generated By:</span>
                {/** Lastname, Firstname M.I */}
                <span className="text-center border-b border-black px-5">
                    {user?.lastname}, {user?.firstname}
                </span>
                <Separator orientation="horizontal"/>
                {/** Position  */}
                <span className="text-center">
                    { selectedFarm?.role ? (selectedFarm?.role === "Owner" ? "Farm Owner" : "Staff") : "Staff"}
                </span>
            </div>
        </div>
    </>
}